library(brew)
library(devtools)

cm = as.package("..")
outfile = file(file.path(cm$path, "R", "autogenerated.r"), "w")
load_all(cm, export_all = FALSE, quiet = TRUE)

funs = ls("package:checkmate")
funs = funs[grepl("^check[A-Z]", funs)]

get_args = function(sig) {
  paste(Map(function(name, value) {
    if (is.symbol(value))
      return(name)

    if (is.character(value))
      return(sprintf("%s = \"%s\"", name, value))

    if (is.null(value))
       value = "NULL"

    if (is.language(value))
      value = capture.output(print(value))

    return(sprintf("%s = %s", name, value))
  }, name = names(sig), value = sig), collapse = ", ")
}

for (fun in funs) {
  sig = formals(match.fun(fun))
  name = substr(fun, 6L, nchar(fun))
  vars = list(
    fun = fun,
    name_cc = name,
    name_lc = checkmate:::killCamel(name),
    args_with_defaults = get_args(sig),
    args_simple = paste(names(sig), collapse = ", ")
  )

  brew(file = "autogen.brew", output = outfile, envir = list2env(vars))
}

close(outfile)
document(cm)
