library(brew)
library(devtools)

cm = as.package("..")
load_all(cm, quiet = TRUE)
outfile = file(file.path(cm$path, "R", "autogenerated.r"), "w")

funs = ls("package:checkmate")
funs = funs[grepl("^check[A-Z]", funs)]
funs = funs[!grepl("Props$", funs,)]

get_args = function(sig) {
  paste(Map(function(name, value) {
    if (is.symbol(value))
      return(name)

    if (is.null(value)) {
       value = "NULL"
    } else if (is.language(value)) {
      value = capture.output(print(value))
    } else if (is.character(value)) {
      value = sprintf("\"%s\"", value)
    }

    return(sprintf("%s = %s", name, value))
  }, name = names(sig), value = sig), collapse = ", ")
}

for (fun in funs) {
  message(sprintf("Creating functions for '%s'", fun))
  sig = formals(match.fun(fun))
  name = substr(fun, 6L, nchar(fun))
  vars = list(
    fun = fun,
    name_cc = name,
    name_lc = convertCamelCase(name),
    args_with_defaults = get_args(sig),
    args_simple = paste(names(sig), collapse = ", ")
  )

  brew(file = "autogen.brew", output = outfile, envir = list2env(vars))
}

close(outfile)
document("..")
